spring:  
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
   #开启配置服务发现
  cloud:
    config:
      discovery:
        enabled: true
        #配置服务实例名称
        service-id: CONFIG
    #开启消息服务    
    bus:
      trace:
        enabled: true      
   #消息驱动   
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*" 
ssso:
  user: 李四不和张三
  age: 1111
